# Generated by Django 2.1.4 on 2020-03-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lang',
            field=models.CharField(default='en', max_length=2),
        ),
    ]
