# Generated by Django 2.1.4 on 2020-04-05 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='article',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
