# Generated by Django 2.1.4 on 2020-04-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='summary',
        ),
    ]
