# Generated by Django 2.1.4 on 2020-04-22 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200421_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_articles', to='articles.Article')),
                ('related_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='articles.Article')),
            ],
        ),
    ]
