# Generated by Django 2.1.4 on 2020-04-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_similararticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='similararticle',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
