# Generated by Django 2.1.4 on 2020-04-28 13:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_similararticle_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2020, 4, 28, 13, 55, 40, 608375, tzinfo=utc)),
        ),
    ]
