# Generated by Django 2.1.5 on 2020-04-29 14:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20200428_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 14, 13, 49, 944504, tzinfo=utc)),
        ),
    ]
