# Generated by Django 2.1.5 on 2020-06-16 21:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20200429_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2020, 6, 16, 21, 21, 23, 411549, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
