ignore:
  - "articles/apps.py"
  - "articles/populate_db.py"
  - "articles/views.py"
  - "collector/apps.py"
  - "collector/views.py"
  - "newsgraphql/populate_db.py"
  - "newsgraphql/wsgi.py"
  - "manage.py"
  - "populate_articles.py"
  - "todelete.py"
  - "recommendations/apps.py"
  - "recommendations/views.py"
  - "users/admin.py"
  - "users/apps.py"
  - "users/views.py"