# Generated by Django 2.1.4 on 2020-04-07 16:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_auto_20200405_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='liked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2020, 4, 7, 16, 40, 30, 553853, tzinfo=utc)),
        ),
    ]
