# Generated by Django 2.1.4 on 2020-04-13 15:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_auto_20200407_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2020, 4, 13, 15, 45, 49, 361658, tzinfo=utc)),
        ),
    ]
