# Generated by Django 2.1.4 on 2020-04-13 15:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_auto_20200413_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2020, 4, 13, 15, 52, 35, 88962, tzinfo=utc)),
        ),
    ]
