# Generated by Django 2.1.4 on 2020-04-21 20:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_auto_20200421_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2020, 4, 21, 20, 31, 6, 357407, tzinfo=utc)),
        ),
    ]
