# Generated by Django 2.1.4 on 2020-04-22 02:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_auto_20200421_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 2, 12, 10, 203811, tzinfo=utc)),
        ),
    ]
