# Generated by Django 2.1.4 on 2020-04-22 15:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0011_auto_20200421_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 15, 9, 25, 73231, tzinfo=utc)),
        ),
    ]
