# Generated by Django 2.1.4 on 2020-04-28 13:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0013_auto_20200422_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2020, 4, 28, 13, 55, 40, 612370, tzinfo=utc)),
        ),
    ]
