# Generated by Django 2.1.5 on 2020-04-29 14:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0015_auto_20200428_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 14, 13, 49, 958778, tzinfo=utc)),
        ),
    ]
