# Generated by Django 2.1.5 on 2020-06-16 21:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0017_auto_20200429_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2020, 6, 16, 21, 21, 23, 413152, tzinfo=utc)),
        ),
    ]
