# Generated by Django 2.1.4 on 2020-04-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
